### ISSUE TITLE
Build & push hetzner-baremetal-toolbox container image to https://quay.io/organization/operate-first 

### ISSUE THREAD

**Issue by rbo** [operate-first/hetzner-baremetal-openshift#10]
Please build & push hetzner-baremetal-toolbox container image to https://quay.io/organization/operate-first based on `./Containerfile`

**Comment by rbo** [comment]
@tumido could you configure and build & repo on quay.io? If you like you can add me (https://quay.io/user/rbohne) to the org

**Comment by HumairAK** [comment]
@rbo I invited you as a _creator_ on quay for this org, I think that should allow you to create a repo and push to it, let me know if that works!

**Comment by rbo** [comment]
@HumairAK thanks, I can create a repo at quay.io but do not have enough privileges to link against operate-first github org. I requested the permissions if you don't want to approve. Please setup a [build trigger](https://quay.io/repository/operate-first/hetzner-baremetal-toolbox?tab=builds) on quay.

**Comment by HumairAK** [comment]
@rbo I didn't see a request for permissions anywhere, but I made you admin on that repo -- does that resolve it?

**Comment by rbo** [comment]
Resolved after a quick chat in slack, thanks.

I created a build trigger: [![Docker Repository on Quay](https://quay.io/repository/operate-first/hetzner-baremetal-toolbox/status "Docker Repository on Quay")](https://quay.io/repository/operate-first/hetzner-baremetal-toolbox)

**Comment by rbo** [comment]
ToDo: Adjust documentation and add toolbox information & Link to quay.
