### ISSUE TITLE
Deploy a OpenShift cluster to Hetzner

### ISSUE THREAD

**Issue by goern** [operate-first/hetzner-baremetal-openshift#12]
As an Application Owner using Operate-First Cloud,
I want to use ArgoCD and GitOps,
so that I can deploy my application to `rick.emea.operate-first.cloud.`

**Acceptance Criteria**
- [x] `rick.emea.operate-first.cloud.` is available in ACM
- [x] `rick.emea.operate-first.cloud.` is available in ArgoCD
- [x] access to `rick.emea.operate-first.cloud.` is documented

/kind feature
/priority important-soon
/triage needs-information

**Comment by goern** [comment]
@tumido @rbo let's use this as a tracker issue and link to work products.

mid-term, I'd like to migrate Thoth's STAGE from PSI to emea.o-f.c @harshad16

**Comment by goern** [comment]
/assign @tumido @harshad16 

could you two please coordinate a little bit of refinement for this issue?

**Comment by rbo** [comment]
Cluster `rick.emea.operate-first.cloud` is work-in-progress. We have to clarify what I have to prepare to hand over the cluster into the operator-first operation model.

My thoughts about it:
- Installing OCS/ODF by hand, because of node labelling and selection devices.
- Rollout hetzner NTP configuration. By hand or ArgoCD? 
  Use hetzner ntp server: 
     ```
     server  ntp1.hetzner.de  iburst
     server  ntp2.hetzner.com iburst
     server  ntp3.hetzner.net iburst
     ```
- Cluster configuration via ArgoCD/ACM (Auth provider, Altermanager, Quotas, Limits, Operators)
- It should be possible for Normal use to deploy by hand and play around on the Cluster (without cluster-admin rights!)
- Operator installation should be done via ArgoCD
- Application deployed should also possible via ArgoCD.

**Comment by rbo** [comment]
![rick](https://user-images.githubusercontent.com/36604/123074270-7065fb00-d417-11eb-85e4-a895185a6209.png)

Is ready to rumble!

**Comment by tumido** [comment]
> Installing OCS/ODF by hand, because of node labelling and selection devices.

Not sure about OCS, that seems quite resource demanding. What is ODF?

> Rollout hetzner NTP configuration. By hand or ArgoCD?

Is that deployed via YAMLs? If so, we can do it via ArgoCD.

> Cluster configuration via ArgoCD/ACM (Auth provider, Altermanager, Quotas, Limits, Operators)

Yes!

> It should be possible for Normal use to deploy by hand and play around on the Cluster (without cluster-admin rights!)

Yes, we enable the same on the Zero cluster

> Operator installation should be done via ArgoCD

Will be available after import to ACM automatically

> Application deployed should also possible via ArgoCD.

Will be available after import to ACM automatically

**Comment by rbo** [comment]
> > Installing OCS/ODF by hand, because of node labelling and selection devices.
> 
> Not sure about OCS, that seems quite resource demanding. What is ODF?

OCS == ODF ~ OpenShift Data Foundation former OpenShift Container Storage. (Rebranding)

Yes, OCS is really resource demanding. Unfortunately, we do not have any other solution at Hetzner. 

> 
> > Rollout hetzner NTP configuration. By hand or ArgoCD?
> 
> Is that deployed via YAMLs? If so, we can do it via ArgoCD.

Of course, via a MachineConfig.

> 
> > Cluster configuration via ArgoCD/ACM (Auth provider, Altermanager, Quotas, Limits, Operators)
> 
> Yes!
> 
> > It should be possible for Normal use to deploy by hand and play around on the Cluster (without cluster-admin rights!)
> 
> Yes, we enable the same on the Zero cluster
> 
> > Operator installation should be done via ArgoCD
> 
> Will be available after import to ACM automatically
> 
> > Application deployed should also possible via ArgoCD.
> 
> Will be available after import to ACM automatically

Sounds good, I will install OCS by hand and then we add the cluster to the ACM&ArgoCD.

**Comment by rbo** [comment]
@tumido what's happened with Image Registry Storage, Prometheus Storage all done via ACM/ArgoCD?

**Comment by tumido** [comment]
> Of course, via a MachineConfig.

Something like this? https://github.com/operate-first/apps/tree/master/cluster-scope/base/machineconfiguration.openshift.io/machineconfigs

>  Image Registry Storage, Prometheus Storage all done via ACM/ArgoCD?

Can be. It is definitely preferred: https://github.com/operate-first/apps/blob/master/cluster-scope/base/imageregistry.operator.openshift.io/configs/cluster/config.yaml

**Comment by rbo** [comment]
> > Of course, via a MachineConfig.
> 
> Something like this? https://github.com/operate-first/apps/tree/master/cluster-scope/base/machineconfiguration.openshift.io/machineconfigs

Exactly, here an "old" Igntion example: https://examples.openshift.pub/cluster-configuration/ntp/ - I can prepare a MachineConfig.

> 
> > Image Registry Storage, Prometheus Storage all done via ACM/ArgoCD?
> 
> Can be. It is definitely preferred: https://github.com/operate-first/apps/blob/master/cluster-scope/base/imageregistry.operator.openshift.io/configs/cluster/config.yaml

Looks good, where is the PVC?

**Comment by tumido** [comment]
> Looks good, where is the PVC?

https://github.com/operate-first/apps/tree/master/cluster-scope/base/core/persistentvolumeclaims

**Comment by rbo** [comment]
Ok, that's the point where I have to learn the folder structure if you have a good starting point. Feel free to share :-)

**Comment by tumido** [comment]
@rbo let's connect rick to our ACM, wdyt? :slightly_smiling_face:

**Comment by rbo** [comment]
Of course, let's do it. We have to ensure that every "customer" namespaces are configured with quotas & co. Self-provisioner should be disabled. What's with the #14 Storage issue?

**Comment by tumido** [comment]
Rick was imported into the ACM and ArgoCD via ACM brigde was enabled. It's enabled to be consumed and populated via our ArgoCD. Documentation and Cluster resources seed PRs are pending.
