### ISSUE TITLE
deploy to hetzner cloud

### ISSUE THREAD

**Issue by durandom** [operate-first/hetzner-baremetal-openshift#15]
Let's investigate costs and technical feasibility for deploying OCP into the hetzner cloud

https://www.hetzner.com/cloud

@rbo do we have a link to the current setup and pricing of the rick cluster (in terms of sizing and machines)

How does the block storage advertised there integrate into OCP. They talk about ceph volumes in their FAQ

**Comment by rbo** [comment]
Here is the current sizing: 

Role | Amount   | Type         | CPU         | RAM         | Disks |
------------ |------------ | ------------- | ------------- | ------------- | -------------
Master |3             | SB48       | Intel Core i7-7700 | 64GB | 2x SSD SATA 256 GB
Worker | 3 | SB94 |  Intel Xeon E5-1650V3 | 256GB | 2x SSD SATA 480 GB

Source: https://github.com/operate-first/hetzner-baremetal-openshift/issues/6#issuecomment-866205831

**Comment by rbo** [comment]
Quick calculation with dedicated vCPU: 1186.08 Euro per Month
 * Master: 3x CCX32 - 83.18 ~ 249.54
 * Worker: 3x CCX51 (128GB RAM & 32 vCPU) - 312.18 ~ 936.54

**Comment by rbo** [comment]
We have two clusters in EMEA Rick & Mory on hetzner and one on AWS. I guess we don't need hetzner cloud.
