### ISSUE TITLE
Cluster/hardware sizing

### ISSUE THREAD

**Issue by rbo** [operate-first/hetzner-baremetal-openshift#6]
We have to clarify the cluster/hardware sizing.

Initially, for development & testing, I started with:

Amount   | Type         | CPU         | RAM         | Disks |
------------ | ------------- | ------------- | ------------- | -------------
3             | SB48       | Intel Core i7-7700 | 64GB | 2x SSD SATA 256 GB
1             | SB49       | Intel Core i7-6700 | 64GB | 2x SSD SATA 256 GB

**Comment by tumido** [comment]
How many clusters we plan on deploying in Hetzner? Can we get more than one?

Also, I think Operate First would appreciate clusters dedicated to:
- storage (minimal HW requirements as per [OCS docs here](https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.7/html-single/planning_your_deployment/index#resource-requirements_rhocs) with raw capacity in tens of TiBs)
- computing/GPUs focused (at least similar to MOC Zero cluster - 9 nodes, in total: 260CPU cores, 400 GiB RAM, no storage needed + GPUs)

/cc @durandom @goern

**Comment by rbo** [comment]
> How many clusters we plan on deploying in Hetzner? Can we get more than one?
> 
> Also, I think Operate First would appreciate clusters dedicated to:
> 
> * storage (minimal HW requirements as per [OCS docs here](https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.7/html-single/planning_your_deployment/index#resource-requirements_rhocs) with raw capacity in tens of TiBs)

Maybe we can try to use a [compact deployment](https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.7/html-single/planning_your_deployment/index#compact-deployment-resource-requirements). 
Don't want to waste too many resources on the control plane. 

We can choose one of the [AX* Servers](https://www.hetzner.com/de/dedicated-rootserver/matrix-ax). Minimum AX51-NVME or higher.  

> * computing/GPUs focused (at least similar to MOC Zero cluster - 9 nodes, in total: 260CPU cores, 400 GiB RAM, no storage needed + GPUs)

Sadly GPU is not available at Hetzner.

Controle Plane I recommend AX41-NVME or AX51-NVME
Infra Nodes: depend on what we want to deploy: OpenShift Logging? 
Compute: AX101 or AX161

Maybe it makes sense to set up only one cluster to save resources ~ budget.

Try to get some cheap servers from the [Serverbörse](https://www.hetzner.com/sb?country=de)

> 
> /cc @durandom @goern

**Comment by durandom** [comment]
Let's think about our user base for this deployment.
The audience would be solution architects and others, get a namespace and you can do whatever you want. 
A little bit more relaxed than the zero cluster. 
And we should make sure we're running always at 80% capacity, since we pay for it. Therefore I'd start with the smallest supported setup and then grow by demand.

**Comment by goern** [comment]
BTW it look like we need some GPU for https://github.com/AICoE/Varangian 
If no GPU is agailable at hetzner, @durandom do we get them from AWS?

**Comment by rbo** [comment]
Because of #8, we decided to start with: 
Role | Amount   | Type         | CPU         | RAM         | Disks |
------------ |------------ | ------------- | ------------- | ------------- | -------------
Master |3             | SB48       | Intel Core i7-7700 | 64GB | 2x SSD SATA 256 GB
Worker | 3 | SB94 |  Intel Xeon E5-1650V3 | 256GB | 2x SSD SATA 480 GB

One of the workers will be used as a bootstrap during installation and added to the cluster after installation.

**Comment by rbo** [comment]
initial sizing is done.  We can close the issue.
